* Auth-Source-Gopass Emacs Package

[[https://www.gnu.org/licenses/gpl-3.0][https://img.shields.io/badge/License-GPL%20v3-blue.svg]]
[[http://melpa.org/#/auth-source-gopass][http://melpa.org/packages/auth-source-gopass-badge.svg]]

This package provides [[https://www.gopass.pw/][gopass - the team password manager]] as an auth-source for emacs. This could be used with packages like eg. smtpmail to provide passwords for the smtp-user. It is a drop-in replacement for the default auth-info source.

This package does not provide any caching or interactive selection of the gopass entries. Each query has to resolve exactly one
entry (right now).

** Usage

This package could be enabled by using the following line:

#+BEGIN_SRC elisp
(auth-source-gopass-enable)
#+END_SRC

** Configuration

This package provides some parameters as well as a function, which can be customized to reflect you personal use-case.

- -auth-source-gopass-path-prefix- :: Default value "accounts"
  Prefix of all entries in the gopass backend.

- -auth-source-gopass-path-separator- :: Default value "/"
  Separator of elements in the gopass backend structure.

- -auth-source-gopass-executable- :: Default value "gopass"
  Executable used for gopass.
